# Descriptions courtes des icônes : ce qui est préréglé, ce qu'il reste à régler, et quoi changer selon le symptôme.
# Le détail (méthode, explications, sources) est dans docs/pixinsight-workflow.html (fiches « Paramètres des outils »).
NB = ('RSHO', 'SHO', 'HOO')
PAGE = ' Détails : page docs/pixinsight-workflow.html.'

# nom de base -> (préréglé, à régler, [si ... -> ...])
S = {
    'LinearPatternSubtraction': ("script LPS_UnClic (moteur de Vicent Peris, sans dialogue) : lignes, Correct the entire image, Layers to remove 9, Rejection limit 3, Global rejection 5, zone de fond choisie automatiquement (la plus sombre), fenêtres de travail fermées, TOUTES les images ouvertes corrigées (allOpenImages = true)",
             "une seule fois par ordinateur (Mac ou PC) : crée le dossier clodoweg dans src/scripts de PixInsight (à côté de PatternCorrection ; Mac : /Applications/PixInsight/src/scripts/clodoweg, PC : en général C:\\Program Files\\PixInsight\\src\\scripts\\clodoweg ; pas le dossier scripts du premier niveau) et copies-y LPS_UnClic.js ; ensuite ouvre les masters linéaires de la cible (et rien d'autre), puis glisse l'icône sur l'un d'eux : tous sont corrigés, avant le recadrage (la correction se fait dans les images)",
             ["corriger des colonnes -> correctColumns = true dans l'icône",
              "une seule image -> allOpenImages = false dans l'icône, puis glisse-la sur l'image",
              "artefacts -> Ctrl+Z : le script est conçu pour les brutes, avant alignement",
              "script introuvable -> vérifie le dossier scripts/clodoweg (à recopier après une réinstallation de PixInsight) ; version avec dialogue : menu Script › Pattern Correction › LinearPatternSubtraction"]),
    'WBPP': ("rien (WBPP garde ses propres réglages)",
             "Maximum quality ; CosmeticCorrection = icône CC_auto ; PSF Signal Weight ; Local normalization activée ; Rejection Auto ; Large-scale rejection High ; pas de drizzle (sauf FWHM < 2 px)",
             ["un groupe de lights sans dark ou flat (onglet Calibration) -> corrige avant Run", "plusieurs nuits -> Grouping keywords = SESSION"]),
    'CC_auto': ("Auto detect, Hot sigma 2,5, Cold désactivé",
                "rien ; choisis cette icône comme modèle Cosmetic correction dans WBPP ; coche CFA seulement en caméra couleur",
                ["petites étoiles modifiées -> Hot sigma 3,0", "S, H, O en poses longues -> 2,2"]),
    'DynamicCrop': ("rien (le cadre dépend de ton image)",
                    "trace le cadre sur un master en excluant les bords bruités, crée une icône, applique-la à tous les masters", []),
    'ImageSolver': ("script ImageSolver_Date.js en une seule icône (pas de conteneur) : date d'observation 2020-01-01 ajoutée seulement si l'image n'en a pas, puis ImageSolver 6.4.2 lancé avec focale 2 939 mm, pixel 3,76 µm (0,264″/px), catalogue automatique (Gaia DR3 local), correction de distorsion ; coordonnées et vraie date lues dans l'image",
                    "une seule fois par ordinateur : copie la NOUVELLE version d'ImageSolver_Date.js dans src/scripts/clodoweg ; ensuite glisse l'icône sur CHAQUE image à calibrer, juste avant SPFC ou SPCC : image RGB combinée, master L, masters H, O et S",
                    ["la date est ajoutée mais ImageSolver ne se lance pas -> glisse l'icône ImageSolver_seul (options) sur la même image",
                     "échec sans coordonnées dans l'en-tête -> lance ImageSolver depuis le menu Script et utilise Search (nom de l'objet)",
                     "master en bin 2 -> metadata_xpixsz = 7.52 et metadata_resolution = 0.0001466 dans solverParams"]),
    'ImageSolver_seul': ("ImageSolver 6.4.2 seul (mêmes réglages que l'icône ImageSolver, sans l'ajout de date)", "secours : glisse sur l'image si l'icône ImageSolver s'arrête après la date", ["icône bloquée après une mise à jour d'ImageSolver -> efface son champ MD5"]),
    'SPFC_RGB_filtres': ("QE IMX455, filtres Antlia R, G, B, Gaia DR3/SP", "rien ; applique sur l'image RGB combinée linéaire, résolue, avant MGC", []),
    'SPFC_L': ("QE IMX455, Gray = Antlia L, Gaia DR3/SP", "rien ; applique sur le master L linéaire, résolu, avant MGC", []),
    'SPFC_H': ("QE IMX455, Narrowband 656,3 nm, 3 nm", "rien ; applique sur le master H, puis MGC_MARS_H", []),
    'SPFC_O': ("QE IMX455, Narrowband 500,7 nm, 3 nm", "rien ; applique sur le master O, puis MGC_MARS_O", []),
    'SPFC_S': ("QE IMX455, Narrowband 672,4 nm, 3 nm", "rien ; S n'est pas dans MARS : utilise plutôt GradientCorrection ou DBE", []),
    'MGC_MARS': ("Gradient scale 1024, Structure separation 3, Smoothness 1,0, MARS Gray = L et R, G, B (la même icône sert pour L et pour l'image RGB), modèle affiché", "une seule fois par ordinateur : ouvre l'icône, section MARS Database, clique Default Files (copie la liste des préférences de MGC), puis glisse le triangle sur l'icône pour la remplacer et enregistre tes icônes (Save Process Icons) ; à refaire si tu recharges les icônes de la fiche ; ensuite après SPFC, sur l'image linéaire",
                 ["erreur « No MARS database files have been selected » -> Default Files dans la section MARS Database", "« 0 reference image(s) available » ou « No reference data found » -> cible hors de MARS (sud au-delà de −15° environ) : GradientCorrection ou DBE à la place de SPFC + MGC", "gradient restant dans les coins -> Gradient scale 512 puis 256", "modèle qui ondule -> Smoothness 3 à 5", "image couleur -> filtres MARS R, G, B"]),
    'MGC_MARS_H': ("comme MGC_MARS, filtre MARS Gray = Ha", "une seule fois par ordinateur : ouvre l'icône, section MARS Database, clique Default Files (copie la liste des préférences de MGC), puis glisse le triangle sur l'icône pour la remplacer et enregistre tes icônes (Save Process Icons) ; à refaire si tu recharges les icônes de la fiche ; ensuite après SPFC_H, sur le master H",
                   ["cible au sud au-delà de −15° environ (et narrowband au-delà de +75°) -> pas de référence MARS : GradientCorrection ou DBE", "gradient restant -> Gradient scale 512 puis 256"]),
    'MGC_MARS_O': ("comme MGC_MARS, filtre MARS Gray = OIII", "une seule fois par ordinateur : ouvre l'icône, section MARS Database, clique Default Files (copie la liste des préférences de MGC), puis glisse le triangle sur l'icône pour la remplacer et enregistre tes icônes (Save Process Icons) ; à refaire si tu recharges les icônes de la fiche ; ensuite après SPFC_O, sur le master O",
                   ["cible au sud au-delà de −15° environ (et narrowband au-delà de +75°) -> pas de référence MARS : GradientCorrection ou DBE", "gradient restant -> Gradient scale 512 puis 256"]),
    'GradientCorrection': ("valeurs par défaut, Structure protection activée", "rien ; contrôle le modèle de gradient",
                           ["gradient dans les coins -> baisse Gradient scale", "nébuleuse assombrie -> monte Protection amount"]),
    'DBE': ("15 points par ligne, rayon 15, Tolerance 0,5, Smoothing 0,25, Subtraction", "Generate, retire les points sur l'objet, ajoute-en dans le fond vide",
            ["points rouges -> Tolerance 1,0 à 1,5", "vignettage -> Division"]),
    'Combinaison_RGB': ("script Combiner_RGB : R, G, B -> image couleur 'RGB', en-tête FITS du rouge copié (coordonnées et date pour ImageSolver), puis R, G et B fermées sans demander d'enregistrer", "une seule fois par ordinateur : copie Combiner_RGB.js dans src/scripts/clodoweg ; nomme tes masters R, G et B, enregistre-les si tu veux garder une version modifiée (après LPS par exemple), puis lance l'icône", ["garder R, G et B ouvertes -> closeSources = false dans l'icône", "une image 'RGB' existe déjà -> ferme-la ou renomme-la"]),
    'Renommer_auto': ("script Renommer_auto : renomme les masters mono ouverts L, R, G, B, H, O, S d'après le mot-clé FILTER (Lum, Red, Ha, OIII...), sinon d'après le nom du fichier", "une seule fois par ordinateur : copie Renommer_auto.js dans src/scripts/clodoweg ; ouvre tes masters, puis lance l'icône", ["filtre inconnu ou nom déjà pris -> message dans la console, renomme cette vue à la main"]),
    'Combinaison_SHO': ("R = S, G = H, B = O, image 'SHO'", "nomme tes masters S, H et O", []),
    'Combinaison_HOO': ("R = H, G = O, B = O, image 'HOO'", "nomme tes masters H et O", []),
    'Masters_S_H_O': ("rien (icône-note)", "renomme tes masters S, H et O ; même recadrage pour tous", []),
    'Masters_H_O': ("rien (icône-note)", "renomme tes masters H et O ; même recadrage", []),
    'DualBand_H': ("H = canal rouge de l'image couleur", "glisse sur l'image dual-band (caméra couleur seulement)", []),
    'DualBand_O': ("O = moyenne de G et B", "glisse sur l'image dual-band (caméra couleur seulement)", []),
    'Find_Background': ("rien", "glisse sur l'image : crée l'aperçu Background ; dans SPCC, Region of Interest › From Preview", []),
    'SPCC': ("Average Spiral Galaxy, QE IMX455, filtres Antlia R, G, B, neutralisation du fond (−2,80 / +2,00), Gaia DR3/SP", "rien ; sur le RGB linéaire, après BXT Correct Only",
             ["champ rempli de nébuleuse -> aperçu Background (Find Background) en Region of Interest"]),
    'BXT_CorrectOnly': ("Correct Only coché", "rien ; sur le RGB combiné linéaire, AVANT SPCC", []),
    'BXT_RGB': ("Sharpen Stars 0,25, Halos 0, Nonstellar 0,50, PSF auto", "rien ; après SPCC, en linéaire",
                ["vers ou pores à 100 % -> Nonstellar 0,40", "halos sombres -> Sharpen Stars plus bas ou Halos plus haut"]),
    'BXT_L': ("Sharpen Stars 0,25, Halos 0, Nonstellar 0,80, PSF auto", "rien ; sur L linéaire, gradient retiré",
              ["vers ou pores -> Nonstellar 0,70", "FWHM > 8 px (~2,1″ au CDK17 en bin 1) -> bin 2 ou réduction ×0,5 avant"]),
    'BXT_L_H': ("Sharpen Stars 0,25, Halos 0, Nonstellar 0,80, PSF auto", "rien ; sur L puis sur H, linéaires, avant tout mélange",
                ["vers ou pores -> Nonstellar 0,70", "FWHM > 8 px -> bin 2 ou réduction ×0,5 avant"]),
    'BXT_NB': ("Sharpen Stars 0,25, Halos 0, Nonstellar 0,60, PSF auto", "rien ; sur la combinaison simple (un filtre par canal), avant tout boost",
               ["artefacts dans O ou S -> Nonstellar 0,50", "FWHM > 8 px -> bin 2 ou réduction ×0,5 avant"]),
    'SXT_lineaire': ("Generate star image coché, Unscreen décoché, Large overlap décoché", "rien ; en linéaire, juste après BXT",
                     ["quadrillage -> Large overlap", "cœur de galaxie retiré -> masque noir sur le cœur"]),
    'SXT_RGB_lineaire': ("Generate star image coché, Unscreen décoché", "rien ; sur le RGB linéaire calibré ; garde seulement l'image d'étoiles", []),
    'NXT_RGB': ("Denoise 0,80, 1 itération, séparations décochées", "rien ; après BXT",
                ["aspect plastique -> 0,70", "taches de couleur -> Color separation, Denoise color plus haut"]),
    'NXT_L': ("Denoise 0,60, 1 itération", "rien ; après BXT", ["détail fin perdu -> 0,50", "encore bruité -> 0,70"]),
    'NXT_H': ("Denoise 0,60, 1 itération", "rien", ["encore bruité -> 0,70", "aspect plastique -> 0,50"]),
    'NXT_O_S': ("Denoise 0,75, 1 itération", "rien", ["très bruité -> 2 itérations", "aspect plastique -> 0,60"]),
    'NXT_final': ("Denoise 0,40, 1 itération", "seulement si du bruit reste sur l'image finale", ["aspect plastique -> 0,30"]),
    'LinearFit_ref_H': ("référence = vue H", "applique sur O puis sur S", []),
    'Extraire_H': ("canal -> vue mono 'H'", "renomme d'abord un master déjà nommé H (ex. H_lin)", []),
    'Extraire_O': ("canal -> vue mono 'O'", "renomme d'abord un master déjà nommé O", []),
    'Extraire_S': ("canal -> vue mono 'S'", "renomme d'abord un master déjà nommé S", []),
    'Extraire_H_stars': ("canal -> vue 'H_stars'", "glisse sur l'image d'étoiles SHO linéaire", []),
    'Extraire_O_stars': ("canal -> vue 'O_stars'", "glisse sur l'image d'étoiles SHO linéaire", []),
    'Extraire_S_stars': ("canal -> vue 'S_stars'", "glisse sur l'image d'étoiles SHO linéaire", []),
    'Continuum_H': ("k = 0,9 ; crée H_cs", "vues nommées H et R (linéaires) ; ajuste k de 0,8 à 1",
                    ["étoiles ou disque encore visibles dans H_cs -> monte k", "H_cs trop sombre ou négatif -> baisse k"]),
    'Continuum_auto': ("Starry, sortie linéaire, pas de réduction de bruit", "choisis H et R dans le dialogue", []),
    'H_dans_RGB': ("w = 1,0 ; R' = R + w·H_cs", "glisse sur le RGB linéaire calibré ; w entre 0,5 et 2",
                   ["régions HII rouge vif -> baisse w", "invisibles -> monte w"]),
    'H_dans_L': ("a = 1,0 ; L = max(L, a·H_cs), sur L elle-même", "glisse sur L ; H_cs doit exister", ["couleurs délavées -> baisse a"]),
    'NBRGBCombination': ("rien (icône-note)", "RGB bande 100 nm, H bande 3 nm, Scale 1,2", ["H trop discret -> Scale 3 à 5"]),
    'GHS_1_premier': ("b = 10, Stretch factor 0 (aucun effet tant que tu ne le montes pas)",
                      "clique le fond ou le signal faible et Send to SP ; Stretch factor jusqu'au pic à 0,25 (fond lu 0,001 -> 6,5 ; 0,002 -> 5,5 ; 0,005 -> 4,5 ; 0,01 -> 3,5)",
                      ["fond bruité qui ressort -> SP trop bas, remonte-le", "cœur brillant qui sature -> baisse HP"]),
    'GHS_2_contraste': ("b = 4, HP 0,9, Stretch factor 1, SP 0,35", "SP = valeur de ta zone plate, au-dessus du fond (souvent 0,30–0,45 ; jamais 0,25 = le fond) ; Stretch factor 1 à 2",
                        ["cœur brillant qui sature -> baisse HP vers sa valeur", "fond trop sombre -> monte LP vers sa valeur (pas au-dessus de SP)", "fond bruité qui ressort -> SP trop bas"]),
    'GHS_3_fond': ("b = 10, SP = HP = 0,20, Stretch factor 1 (fond à 0,23 après GHS_2)", "SP = HP = fond lu - 0,03 (0,22 après Statistical Stretch à 0,25) ; Stretch factor 0,8 à 1,2 jusqu'au fond vers 0,12–0,14", []),
    'Statistical_Stretch': ("Target Median 0,25, Blackpoint Sigma 5, Linked coché, reste par défaut", "rien ; alternative à GHS ; avec 0,25, passe ensuite GHS_3_fond (fond vers 0,12–0,14)",
                            ["cible compacte (galaxie) -> Target Median 0,10", "fond trop clair -> Blackpoint Sigma plus haut"]),
    'LRGB_ajout_L': ("seul L coché, Lightness 0,5, Saturation 0,35, réduction du bruit de chrominance", "vue L nommée 'L' ; glisse sur le RGB sans étoiles",
                     ["couleurs délavées -> étire L moins fort"]),
    'H_en_luminance': ("seul L coché, Lightness 0,5, Saturation 0,40", "copie de H étiré nommée 'L' ; glisse sur l'image HOO", []),
    'Masque_L': ("script Masque_auto : crée 'masque_L' (fond coupé à s = 0,14, flou 2 px) et l'ATTACHE à l'image", "glisse sur l'image sans étoiles étirée ; s = fond mesuré + 0,01 ; plus de Ctrl+M",
                 ["fond du masque au-dessus de 0,05 -> monte s", "copie Masque_auto.js dans src/scripts/clodoweg"]),
    'Masque_retirer': ("script Masque_auto en mode retirer : détache le masque et ferme masque_L", "glisse sur la même image, après Courbes et LHE (déjà inclus dans C_Finition et les Boost)", []),
    'Courbes': ("courbe en S (0,25 -> 0,19 ; 0,75 -> 0,81), saturation 0,5 -> 0,65", "sous Masque_L ; une seule passe",
                ["trop saturé -> S à 0,60", "couleurs ternes -> S à 0,72", "pas assez -> option Boost_finition", "fond qui se colore -> vérifie le masque"]),
    'LHE': ("Kernel 150, Contrast limit 2,0, Amount 0,30, 12-bit, circulaire", "sous Masque_L ; passe 1 (grandes structures), LHE_fin ensuite",
            ["effet artificiel ou halo sombre -> Amount 0,20", "bruit -> Contrast limit 1,5", "anneaux -> Kernel plus grand"]),
    'LHE_fin': ("Kernel 40, Contrast limit 2,0, Amount 0,25, 10-bit, circulaire", "sous Masque_L, après LHE ; passe 2 (petits détails)",
            ["bruit ou aspect gravé -> Amount 0,20 (0,16)", "pas assez de détail fin -> 0,30"]),
    'Boost_finition_light': ("conteneur : courbe très légère (0,25 -> 0,24 ; 0,75 -> 0,76, saturation 0,5 -> 0,57) puis LHE rayon 80, Amount 0,12", "sous Masque_L, après LHE_fin ; un glisser = un petit cran", ["pas assez -> un deuxième passage, ou Boost_finition"]),
    'Boost_finition': ("conteneur : petite courbe (0,25 -> 0,23 ; 0,75 -> 0,77, saturation 0,5 -> 0,60) puis LHE rayon 80, Amount 0,20", "sous Masque_L, après LHE_fin ; un glisser = un petit cran, rejoue-le pour pousser encore",
                       ["fond qui se colore ou bruit -> arrête, ou NXT final", "halo sombre autour de la galaxie -> une passe de moins"]),
    'ICC_sRGB': ("ICCProfileTransformation : vers sRGB IEC61966-2.1, Convert to the specified profile, rendu Perceptual, compensation du point noir", "glisse sur l'image finie avant l'export (Export_TIFF le fait aussi sur sa copie : cette icône sert si tu enregistres toi-même)", ["impression ou Adobe RGB voulu -> change le profil cible dans l'icône"]),
    'Export_TIFF': ("script Export_TIFF : copie de l'image en entiers 16 bits, convertie en sRGB IEC61966-2.1 (icc = true), enregistrée en TIFF (.tiff) sous le NOM DE L'OBJET, sans espace (NGC 1532 -> NGC1532), = nom du dossier des masters ouverts (L, R, G, B, H…), dossiers génériques (master, lights, output, WBPP…) sautés ; enregistrée dans ce dossier ; l'image ouverte ne change pas", "glisse sur l'image finie (après C_Fond_final), L encore ouverte ; copie Export_TIFF.js dans src/scripts/clodoweg",
                    ["aucun master ouvert -> mot-clé OBJECT, sinon nom de la vue, dans ton dossier personnel", "autre nom -> remplis nom", "autre dossier -> remplis dossier", "garder plusieurs versions -> suffixe (ex. _v2)", "garder le profil actuel -> icc false"]),
    'Nettoyage_sans_etoiles': ("script Nettoyage_sans_etoiles (calcul sur une copie à 2000 px) : seules les étoiles BRILLANTES de RGB_stars comptent (luminance floutée 20 px au-dessus de 0,05 à 0,12), zone étendue au halo ; fond LOCAL par ouverture morphologique (disque 25 px, 3 passes : taches de moins de 75 px retirées, halo de la galaxie gardé) ; galaxie et structures claires protégées ; excès au-dessus du fond local retiré, bruit fin gardé", "glisse sur l'image sans étoiles juste après LRGB, AVANT HDRMT_40 ; RGB_stars doit être ouverte ; vérifie à 1:1, Ctrl+Z pour annuler",
                               ["voir ce qui est touché -> afficherMasque true (vue masque_nettoyage : seulement les grandes étoiles)", "trop d'étoiles touchées -> seuilBas 0,07, seuilHaut 0,15", "halo d'une étoile moyenne encore visible -> seuilBas 0,04, seuilHaut 0,09", "grand halo encore visible -> passes 5", "bras ou petite galaxie atténué -> structure 0,10"]),
    'HDRMT_40': ("conteneur : copie de l'image (vue HDR_avant), HDRMT 6 couches To lightness / Preserve hue / Lightness mask, mélange 0,4 × résultat + 0,6 × copie, copie fermée", "PARTIE 1 de la finition (cœur) : glisse sur l'image sans étoiles étirée, AVANT C_Finition ; options à la place : HDRMT_50 (cœur brûlé) ou HDRMT_eclat (cœur terne)",
                 ["cœur encore brûlé -> HDRMT_50 à la place", "cœur détaillé mais terne -> HDRMT_eclat à la place", "cœur déjà bien -> saute cette icône"]),
    'NXT_final_doux': ("Denoise 0,25, 1 itération", "PARTIE 3 (bruit), à la place de NXT_final : glisse sur l'image sans étoiles finie", ["encore trop lissé -> saute la partie 3"]),
    'NXT_final_fort': ("Denoise 0,60, 1 itération", "PARTIE 3 (bruit), à la place de NXT_final : glisse sur l'image sans étoiles finie", ["aspect plastique -> NXT_final (0,40)"]),
    'Fond_auto_clair': ("script Fond_auto, cible 0,14 : fond de chaque canal mesuré (grille 8 × 8), amené à 0,14 par mtf, sans écrêtage ; fond neutre", "PARTIE 5 (fond), à la place de C_Fond_final si l'image est trop sombre : glisse sur l'image finie, étoiles comprises, puis Fond_desature",
                        ["fond encore trop sombre -> double-clic, cible 0,15"]),
    'HDRMT_30': ("conteneur : copie de l'image (vue HDR_avant), HDRMT 6 couches To lightness / Preserve hue / Lightness mask, mélange 0,3 × résultat + 0,7 × copie, puis fermeture de la copie", "glisse sur l'image sans étoiles étirée ; en galaxie : partie 1, à la place de HDRMT_40 ; la copie HDR_avant est fermée automatiquement",
                 ["cœur encore trop clair -> HDRMT_40 ou HDRMT_50", "aucun effet visible -> saute la partie 1"]),
    'HDRMT_50': ("conteneur : copie de l'image (vue HDR_avant), HDRMT 6 couches To lightness / Preserve hue / Lightness mask, mélange 0,5 × résultat + 0,5 × copie, puis fermeture de la copie", "glisse sur l'image sans étoiles étirée ; la copie HDR_avant est fermée automatiquement à la fin (script Fermer_vues)", ["effet trop faible -> a = 0,7 dans HDR_melange", "trop fort -> a = 0,3"]),
    'SXT_L_lineaire': ("StarXTerminator, Unscreen décoché, sur L linéaire ; Generate star image coché", "rien ; dans C_L_lineaire après BXT_L ; garde L_stars (linéaire) ouverte pour Etoiles_LRGB", ["quadrillage -> Large overlap"]),
    'SXT_L_etire': ("StarXTerminator, Unscreen coché, sur L étirée", "glisse sur L après l'étirement (GHS ou Statistical Stretch, puis GHS_3_fond) ; garde L_stars ouverte pour Etoiles_LRGB_etire", []),
    'Etoiles_LRGB_etire': ("script Etoiles_LRGB : 0,5 × L_stars (déjà étirée) + 0,5 × luminance RGB appliquée à RGB_stars (saturation 0,35), puis L_stars fermée", "après Star_Stretch sur RGB_stars et SXT_L_etire ; glisse sur n'importe quelle image",
                           ["anneau ou cœurs trop blancs -> partL 0,3"]),
    'Fond_desature': ("script Fond_desature : fond mesuré ; zones faibles (luminance lissée sous fond + 0,15, décroissant jusqu'à + 0,30) : violet neutralisé (G remonté jusqu'à min(R, B), magenta seulement) ; fond (sous + 0,03, rampe jusqu'à + 0,15) : couleur retirée", "glisse sur l'image finie, étoiles comprises ; dernière étape",
                      ["violet encore visible dans le halo -> violetFin 0,40", "extensions faibles de la galaxie grisées -> fin 0,10"]),
    'Boost_final': ("conteneur : masque de luminance tiré de L sans étoiles (script Masque_auto, source = L, s = 0,20, gamma 2 : fort sur le cœur et les bras brillants, faible sur le halo et les bras faibles ; étoiles de RGB_stars retirées du masque) attaché, CurvesTransformation c 0,46094 -> 0,53646 et S 0,46354 -> 0,54167, masque retiré", "glisse sur l'image finie avec étoiles ; L (sans étoiles, étirée) doit être ouverte",
                    ["masque encore trop large -> gamma 3 dans Masque_L_source", "trop fort -> rapproche les points de la diagonale", "étoiles touchées -> vérifie que L est bien la version sans étoiles"]),
    'HDRMT_eclat': ("conteneur : HDRMT à 40 % (copie HDR_avant, HDRMT 6 couches, mélange 0,4 × résultat + 0,6 × copie, copie fermée), puis Boost_finition_light (masque, courbe très légère, saturation 0,57, LHE rayon 80 Amount 0,12, masque retiré)", "glisse sur l'image sans étoiles étirée, à la place de HDRMT_50 ; HDRMT rend le détail du cœur, le Boost lui rend son éclat",
                    ["cœur encore terne -> un Boost_finition_light de plus", "pas assez de détail -> a = 0,5 à 0,7 dans HDR_melange", "trop sombre ou gris -> a = 0,3"]),
    'HDRMT': ("6 couches, 1 itération, To lightness, Preserve hue, Lightness mask", "rien",
              ["pas assez -> 2 itérations", "trop fort -> mélange 50 % avec l'original"]),
    'NBN_SHO': ("palette SHO, boosts à 0", "Lightness = H ; Shadowpoint pour un fond gris foncé ; O3 puis S2 boost peu à peu",
                ["trop vert -> SCNR partiel", "O discret -> O3 boost"]),
    'NBN_HOO': ("palette HOO, boost à 0", "Lightness = H ; Shadowpoint ; O3 boost peu à peu", ["tout rouge -> O3 boost"]),
    'Foraxx_SHO': ("formule Foraxx SHO, image 'SHO_Foraxx'", "vues S, H, O étirées, sans étoiles, fonds proches", []),
    'Foraxx_HOO': ("formule Foraxx HOO, image 'HOO_Foraxx'", "vues H et O étirées, sans étoiles", []),
    'HOO_simple': ("R = H, G = O, B = O", "vues H et O étirées", []),
    'HOO_Hubble': ("G = 0,6·H + 0,4·O", "vues H et O étirées ; ajuste les coefficients", []),
    'Perfect_Palette_Picker': ("rien (le script ne lit pas l'icône)", "choisis H, O, S ; Linear Input Data selon tes images ; compare les 16 vignettes", []),
    'NBColourMapper': ("rien (icône-note)", "H rouge-orangé, O cyan-bleu, S rouge profond ou or", []),
    'SCNR_SHO': ("vert, Average Neutral, Amount 0,70", "rien", ["encore vert -> 0,80", "trop magenta -> 0,50"]),
    'Etoiles_RGB': ("rien (icône-note)", "suis les icônes suivantes : étoiles RGB calibrées pour l'image SHO", []),
    'Etoiles_HOO': ("rien (icône-note)", "avec RGB : étoiles RGB ; sans RGB : étoiles de SXT, NB to RGB ou étoiles synthétiques", []),
    'Etoiles_HOO_synth': ("R = H_stars, G = 0,2·H_stars + 0,8·O_stars, B = O_stars", "vues d'étoiles linéaires H_stars et O_stars",
                          ["étoiles bleues verdâtres -> 0,3·H + 0,7·O"]),
    'NB_to_RGB_Stars': ("rien (le script ne relit pas l'icône)", "étoiles H et O (S en option), linéaires ; Apply Star Stretch 5 / 1,0",
                        ["étoiles bleues verdâtres -> active le ratio et monte-le"]),
    'Star_Stretch': ("Stretch Amount 6, Color Boost 1,3, Remove Green (SCNR) coché", "rien ; sur l'image d'étoiles linéaire",
                     ["cœurs d'étoiles blancs (R = G = B = 1) -> 5,5", "étoiles trop grosses -> 5 ou 4", "étoiles grisées par le SCNR -> décoche Remove Green", "étoiles criardes -> Color Boost 1,0"]),
    'Etoiles_screen': ("~((~$T) * (~RGB_stars)), sur l'image elle-même", "glisse sur l'image sans étoiles finale : elle reçoit les étoiles ; étoiles étirées nommées RGB_stars (nom donné par SXT, s minuscule)", ["autre nom d'étoiles -> corrige-le dans la formule"]),
    'CorrectMagentaStars': ("Amount 0,8", "rien ; sur l'image SHO finale avec étoiles", ["magenta encore visible -> 1,0"]),
    'Etoiles_reduites': ("S = 0,20 (Bill : 0,15) ; recombinaison screen + réduction Blanshan en une formule, sur l'image elle-même", "À LA PLACE d'Etoiles_screen : glisse sur l'image sans étoiles finale ; étoiles étirées nommées RGB_stars", ["étoiles encore grosses -> S 0,15", "trop petites -> S 0,25, ou Etoiles_screen", "pour recommencer -> Ctrl+Z"]),
    'Fermer_L_stars': ("script Fermer_vues : ferme L_stars (étoiles de la luminance, inutiles)", "rien ; dans le conteneur après SXT sur L", []),
    'Etoiles_auto': ("script Etoiles_auto : étire RGB_stars avec la courbe de Star Stretch (amount 6), saturation 1,3 (0,4 × sur les rouges, 0,7 × sur les cyans), SCNR vert (scnr = true), sans dialogue", "rien ; dernière étape du conteneur RGB rapide, travaille sur la vue RGB_stars",
                     ["étoiles trop grosses ou cœurs blancs -> amount 5,5", "étoiles criardes -> satAmount 1,0", "étoiles ternes ou grisées par le SCNR -> scnr false"]),
    'Etoiles_LRGB': ("script Etoiles_LRGB : L_stars (linéaire) étirée avec la courbe de Star Stretch / Etoiles_auto (amount 6), luminance 0,5 × L_stars + 0,5 × luminance RGB appliquée à RGB_stars par LRGBCombination (saturation 0,35), puis L_stars fermée", "glisse sur n'importe quelle image, après l'étirement des étoiles RGB (Star_Stretch, ou Etoiles_auto en rapide) et avant LRGB_ajout_L ; L_stars vient de SXT sur L linéaire (C_L_lineaire, ou C_L_rapide en rapide) ; saute-la pour garder les étoiles du RGB seul",
                     ["anneau blanc ou coloré autour des étoiles -> partL 0,3, ou n'utilise pas l'option", "cœurs trop blancs -> partL 0,3 ou saturation 0,30", "Star_Stretch réglé à un autre Stretch Amount -> même valeur dans amount"]),
    'STF': ("process ScreenTransferFunction (STF), réglage neutre ; affichage seulement, les pixels ne changent pas", "double-clic sur l'icône : la fenêtre STF s'ouvre ; choisis l'image, puis A (Auto Stretch) ; lien R/G/B : bouton chaîne",
             ["revenir à l'image brute -> Reset de la fenêtre STF (ou F12)", "dominante de couleur à l'écran -> décoche le lien R/G/B (chaîne), puis A"]),
    'Fond_auto': ("script Fond_auto : fond de chaque canal mesuré (grille 8 × 8, quart le plus sombre des cases), puis mtf canal par canal pour l'amener à 0,12, sans écrêtage ; fond neutre", "glisse sur l'image finie, étoiles comprises ; dernière étape ; console : fond avant et après",
                  ["image trop sombre -> cible 0,13 ou 0,14", "données très propres -> 0,10 à 0,11"]),
    'Fermer_vues': ("script Fermer_vues : ferme les vues listées dans le paramètre views", "copie Fermer_vues.js dans src/scripts/clodoweg", []),
    'MT_etoiles': ("Selection 0,25, Amount 0,60, 1 itération, 5×5 circulaire", "sur l'image d'étoiles seule, avant Etoiles_screen", ["trop fort -> Amount 0,50"]),
    'Halo_B_Gon': ("rien (réglages dans le dialogue)", "Select stars-only image = l'image d'étoiles étirée (RGB_stars ; NBtoRGB_stars en SHO ; HOO_stars en HOO), AVANT Etoiles_screen ; Reduction Amount Low ; Linear Data décoché",
                   ["pas assez -> relance en Low (Med = 4 courbes, High = 9)"]),
    # 04 : matériel
    'SPCC_QHY600_Antlia': ("Average Spiral Galaxy, QE IMX455, Antlia V Pro R, G, B, neutralisation du fond, Gaia DR3/SP", "rien ; sur le RGB linéaire",
                           ["champ rempli de nébuleuse -> aperçu Background en Region of Interest"]),
    'SPFC_RGB_QHY600_Antlia': ("QE IMX455, Antlia R, G, B", "rien ; sur le RGB combiné, avant MGC", []),
    'SPFC_L_QHY600_Antlia': ("QE IMX455, Antlia L", "rien ; sur le master L, avant MGC", []),
    'SPFC_H_QHY600_Antlia': ("QE IMX455, 656,3 nm, 3 nm", "rien ; sur le master H, avant MGC_MARS_H", []),
    'SPFC_O_QHY600_Antlia': ("QE IMX455, 500,7 nm, 3 nm", "rien ; sur le master O, avant MGC_MARS_O", []),
    'SPFC_S_QHY600_Antlia': ("QE IMX455, 672,4 nm, 3 nm", "rien ; S hors MARS : GradientCorrection ou DBE", []),
}

# variantes selon le workflow
V = {
    ('LRGB', 'NXT_final'): ("Denoise 0,40, 1 itération", "PARTIE 3 de la finition (bruit) : glisse sur l'image sans étoiles après C_Finition (et le Boost éventuel) ; options à la place : NXT_final_doux (0,25), NXT_final_fort (0,60)", ["aspect plastique -> NXT_final_doux", "bruit encore visible -> NXT_final_fort"]),
    ('LHA', 'NXT_final'): ("Denoise 0,40, 1 itération", "PARTIE 3 de la finition (bruit) : glisse sur l'image sans étoiles après C_Finition (et le Boost éventuel) ; options à la place : NXT_final_doux (0,25), NXT_final_fort (0,60)", ["aspect plastique -> NXT_final_doux", "bruit encore visible -> NXT_final_fort"]),
    ('NB', 'GHS_1_premier'): ("b = 10, Stretch factor 0", "étire H d'abord (pic à 0,25 ; Stretch factor 3,5 à 6,5 selon le fond lu), puis O et S jusqu'au MÊME fond (Stretch factor plus élevé)",
                              ["bruit de O ou S qui ressort -> SP trop bas, remonte-le"]),
    ('LRGB', 'GHS_3_fond'): ('b = 10, SP = HP = 0,20, Stretch factor 1 (fond à 0,23 après GHS_2)', "applique-la au RGB ET à L, mêmes réglages, AVANT LRGB ; SP = HP = fond lu - 0,03 (0,22 après Statistical Stretch à 0,25) ; Stretch factor 0,8 à 1,2 jusqu'au fond vers 0,12–0,14 sur les deux", []),
    ('LHA', 'GHS_3_fond'): ('b = 10, SP = HP = 0,20, Stretch factor 1 (fond à 0,23 après GHS_2)', "applique-la au RGB ET à L, mêmes réglages, AVANT LRGB ; SP = HP = fond lu - 0,03 (0,22 après Statistical Stretch à 0,25) ; Stretch factor 0,8 à 1,2 jusqu'au fond vers 0,12–0,14 sur les deux", []),
    ('LRGB', 'GHS_1_premier'): ('b = 10, Stretch factor 0', "sur L sans étoiles (le RGB passe par Statistical Stretch) ; clique le fond ou le signal faible, Send to SP ; Stretch factor jusqu'au pic à 0,25 (fond lu 0,001 -> 6,5 ; 0,002 -> 5,5 ; 0,005 -> 4,5 ; 0,01 -> 3,5)", ['fond bruité qui ressort -> SP trop bas, remonte-le', 'méthode « GHS sur tout » -> aussi sur le RGB']),
    ('LRGB', 'GHS_2_contraste'): ('b = 4, HP 0,9, Stretch factor 1, SP 0,35', 'sur L ; SP = valeur de ta zone plate, au-dessus du fond (souvent 0,30–0,45 ; jamais 0,25 = le fond) ; Stretch factor 1 à 2', ['cœur brillant qui sature -> baisse HP vers sa valeur', 'fond trop sombre -> monte LP vers sa valeur (pas au-dessus de SP)']),
    ('LRGB', 'Statistical_Stretch'): ('Target Median 0,25, Blackpoint Sigma 5, Linked coché, reste par défaut', 'sur le RGB sans étoiles (L passe par GHS) ; puis GHS_3_fond sur les deux, avant LRGB', ['couleurs ternes -> Saturation plus basse dans LRGB, ou Luma Only coché', 'méthode « Statistical Stretch sur tout » -> aussi sur L, même Target Median']),
    ('LHA', 'GHS_1_premier'): ('b = 10, Stretch factor 0', "sur L sans étoiles (le RGB passe par Statistical Stretch) ; clique le fond ou le signal faible, Send to SP ; Stretch factor jusqu'au pic à 0,25 (fond lu 0,001 -> 6,5 ; 0,002 -> 5,5 ; 0,005 -> 4,5 ; 0,01 -> 3,5)", ['fond bruité qui ressort -> SP trop bas, remonte-le', 'méthode « GHS sur tout » -> aussi sur le RGB']),
    ('LHA', 'GHS_2_contraste'): ('b = 4, HP 0,9, Stretch factor 1, SP 0,35', 'sur L ; SP = valeur de ta zone plate, au-dessus du fond (souvent 0,30–0,45 ; jamais 0,25 = le fond) ; Stretch factor 1 à 2', ['cœur brillant qui sature -> baisse HP vers sa valeur', 'fond trop sombre -> monte LP vers sa valeur (pas au-dessus de SP)']),
    ('LHA', 'Statistical_Stretch'): ('Target Median 0,25, Blackpoint Sigma 5, Linked coché, reste par défaut', 'sur le RGB sans étoiles (L passe par GHS) ; puis GHS_3_fond sur les deux, avant LRGB', ['couleurs ternes -> Saturation plus basse dans LRGB, ou Luma Only coché', 'méthode « Statistical Stretch sur tout » -> aussi sur L, même Target Median']),
    ('SHO', 'Etoiles_screen'): ("~((~$T) * (~NBtoRGB_stars)), sur l'image elle-même", "glisse sur l'image SHO sans étoiles finale ; étoiles de NB to RGB (NBtoRGB_stars), étirées", ["étoiles synthétiques -> remplace par Stars_HOO"]),
    ('HOO', 'Etoiles_screen'): ("~((~$T) * (~HOO_stars)), sur l'image elle-même", "glisse sur l'image HOO sans étoiles finale ; étoiles de SXT sur HOO (HOO_stars), étirées", ["étoiles RGB -> RGB_stars", "NB to RGB -> NBtoRGB_stars", "synthétiques -> Stars_HOO"]),
    ('LHA', 'Combinaison_RGB'): ("script Combiner_RGB : R, G, B -> image couleur 'RGB', en-tête FITS du rouge copié ; R, G et B restent OUVERTES (closeSources = false : R sert à Continuum_H)", "nomme tes masters R, G et B (ou Renommer_auto), puis lance l'icône ; ferme G et B toi-même", []),
    ('SHO', 'Etoiles_reduites'): ("S = 0,20 ; screen + réduction Blanshan avec NBtoRGB_stars, sur l'image elle-même", "à la place d'Etoiles_screen : glisse sur l'image SHO sans étoiles finale", ["étoiles synthétiques -> remplace NBtoRGB_stars par Stars_HOO", "pour recommencer -> Ctrl+Z"]),
    ('HOO', 'Etoiles_reduites'): ("S = 0,20 ; screen + réduction Blanshan avec HOO_stars, sur l'image elle-même", "à la place d'Etoiles_screen : glisse sur l'image HOO sans étoiles finale", ["étoiles RGB -> RGB_stars ; NB to RGB -> NBtoRGB_stars", "pour recommencer -> Ctrl+Z"]),
    ('NB', 'Statistical_Stretch'): ("Target Median 0,25, Blackpoint Sigma 5", "rien ; même Target Median pour tous les masters ; avec 0,25, passe ensuite GHS_3_fond", []),
    ('SHO', 'SXT_lineaire'): ("Generate star image coché, Unscreen décoché", "rien ; garde les DEUX images (fond et étoiles)", ["quadrillage -> Large overlap"]),
    ('RSHO', 'SXT_lineaire'): ("Generate star image coché, Unscreen décoché", "rien ; garde le fond sans étoiles (étoiles prises au RGB)", ["quadrillage -> Large overlap"]),
    ('HOO', 'SXT_lineaire'): ("Generate star image coché, Unscreen décoché", "rien ; garde l'image d'étoiles si tu n'as pas de RGB", ["quadrillage -> Large overlap"]),
    ('LRGB', 'SXT_lineaire'): ("Generate star image coché, Unscreen décoché", "rien ; sur RGB (garde les étoiles) et sur L (jette ses étoiles)", ["quadrillage -> Large overlap"]),
    ('LHA', 'SXT_lineaire'): ("Generate star image coché, Unscreen décoché", "rien ; sur RGB (garde les étoiles) et sur L (jette ses étoiles)", ["quadrillage -> Large overlap"]),
}

LAUNCH = {True: "LANCEMENT : glisse l'icône sur l'image.", False: "LANCEMENT : double-clic sur l'icône, puis Apply Global."}
MD5 = " Si l'icône est bloquée après une mise à jour du script, efface son champ MD5."


def text(prefix, base, drag=None, md5=False):
    """Paragraphes séparés par une ligne vide : LANCEMENT, PRÉRÉGLÉ, À RÉGLER, SI (un cas par ligne), Détails."""
    key = ('NB', base) if prefix in NB and ('NB', base) in V else (prefix, base)
    pre, todo, ifs = V.get(key) or S[base]
    parts = []
    if drag is not None:
        parts.append(LAUNCH[drag] + (MD5 if md5 else ''))
    parts.append("PRÉRÉGLÉ : %s." % pre)
    parts.append("À RÉGLER : %s." % todo)
    if ifs:
        parts.append("SI :\n" + "\n".join("- " + x for x in ifs))
    parts.append(PAGE.strip())
    return "\n\n".join(parts)
